Repository nextcloud/integration_swp, pull requests merged in 2024-12, with the labels that each got.

#12 Add npm audit action
  .github/workflows/npm-audit-fix.yml
Labels: enhancement, automated

#16 Remove trailing space
  src/main.js
Labels: bug, 3. to review

#13 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#14 [stable24] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#21 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
